### ISSUE TITLE
Damn, the front page photos are slow to load

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/doubleunion-dot-org#1]
Let's make them faster

**Comment by brittag** [comment]
This seems ok to me!

**Comment by lilliealbert** [comment]
It's a little embarrassing that the images don't load immediately and you see pink in the background first, so I'm gonna be obnoxious and reopen this.

Alternately, we could redesign the home page with different pictures entirely and make sure that they are optimized from the beginning!

**Comment by Imperiopolis** [comment]
Reduced the size of this image by about 80% :) Should load nice and quick now.

**Comment by brittag** [comment]
Yay for resolving old issues! Thanks!
