### ISSUE TITLE
Mobile site's "hamburger menu" (at top right) doesn't work

### ISSUE THREAD

**Issue by brittag** [doubleunion/doubleunion-dot-org#11]
This happens for me in Safari on iOS 9, and my friend with an Android phone reported it too. I don't know exactly what's supposed to happen, but nothing seems to happen when I tap this button. :)

**Comment by brittag** [comment]
🎉 🎉 🎉  Thank you @Imperiopolis for resolving this ancient issue!

**Comment by Imperiopolis** [comment]
Note that it's still not actually resolved in production until we make the DNS changes to point to the github pages site, but that should happen pretty soon :)
