### ISSUE TITLE
Improve "Membership benefits and responsibilities" text

### ISSUE THREAD

**Issue by anaulin** [doubleunion/doubleunion-dot-org#110]
During the application process we link to the "Membership benefits and responsibilities" on  https://doubleunion.org/membership/.

We should update this section to be more up-to-date (e.g. remove mentions of meetings, maybe re-work the key-member vs member distinction).

We should also verify that there is an anchor tag on that section, so that we can link to that section directly from the application form.

@brittag fyi please add your own notes

**Comment by brittag** [comment]
Yes! We need to tell people that they can get full access to the hypothetical physical space after orientation, and acknowledge that the whole "key member" thing is up in the air until we have a physical space again - that'll need to be on our list of things to update after we have a new space: https://github.com/doubleunion/arooo/issues/538

**Comment by sarahwalters** [comment]
It looks like there are anchor tags on the sections of this page -- e.g. https://doubleunion.org/membership/#membership-benefits-and-responsibilities takes me to the "Membership Benefits and Responsibilities" section.
