### ISSUE TITLE
Deprecate supporters page?

### ISSUE THREAD

**Issue by brittag** [doubleunion/doubleunion-dot-org#13]
[This page with a list of supporters](http://www.doubleunion.org/supporters) is linked from the bottom of our homepage ("We are so grateful to [our supporters](http://www.doubleunion.org/supporters) for helping us thrive!"), but we don't seem to be updating it - should we remove it?

**Comment by lilliealbert** [comment]
done! a2ca556a907ad1376a2c8e5e44f2038b7abdc84e

:ocean: :whale: :sunny: :tropical_fish: :ocean:
