### ISSUE TITLE
"About" page updates

### ISSUE THREAD

**Issue by mathildemouw** [doubleunion/doubleunion-dot-org#32]
- Add newest board member Golden's bio 
- remove Sally's board member bio
- remove Mary's board member bio
- change Dani's title to Treasurer

**Comment by brittag** [comment]
Looking at http://doubleunion.org/about#leadership, this seems done except removing Tina's "Director of Multiculturalism and Inclusion" title.

**Comment by mathildemouw** [comment]
I added that bullet point to https://github.com/doubleunion/doubleunion-dot-org/issues/33 , because I want to remove Tina's title as I add Christina and Elora to the leadership page. I will remove that bullet point from this issue so we can close it!
