### ISSUE TITLE
Donate via Paypal button expiring

### ISSUE THREAD

**Issue by tinacoles** [doubleunion/doubleunion-dot-org#40]
Our fiscal sponsor IAM has been notified by PayPal that effective March 29, 2017, some of their PayPal Donation buttons may no longer work due to changes to the PayPal checkout system.

Please review [this information from PayPal](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ2067&expand=true&locale=en_US) to help determine whether we will need a new button.  Its likely that newer buttons will be fine, but they recommend that all Affiliates review their coding to confirm.

We have two options to ensure that there are no disruptions in using the PayPal coding provided by IAM:  
(1) Revise the coding for the existing button with the information provided by PayPal.
(2) Request a new PayPal button from IAM.  

DU has requested a new PayPal button just in case.

**Comment by brittag** [comment]
Looks like the current button is still fine.
