### ISSUE TITLE
Update the list of board members

### ISSUE THREAD

**Issue by brittag** [doubleunion/doubleunion-dot-org#6]
http://www.doubleunion.org/about - it's missing our new board member. :)

**Comment by lilliealbert** [comment]
@dashland can you give me bio words + the picture you'd like for this page? http://www.doubleunion.org/about

**Comment by lilliealbert** [comment]
@dashland ping :wink:

**Comment by brittag** [comment]
I just checked with @mathildemouw and it sounds like she'll be working on this. :D Yay!

**Comment by brittag** [comment]
This was closed by https://github.com/doubleunion/doubleunion-dot-org/pull/31 - yay!
