### ISSUE TITLE
add social media links prominently

### ISSUE THREAD

**Issue by compwron** [doubleunion/doubleunion-dot-org#97]
https://www.facebook.com/doubleunion
https://twitter.com/doubleunionsf
https://www.instagram.com/doubleunionsf/

**Comment by compwron** [comment]
And add instagram link to "our blog, Twitter, or general interest mailing list" https://www.instagram.com/p/B69krLFBCtK/

**Comment by brittag** [comment]
We could still do better, but this is somewhat improved in https://github.com/doubleunion/doubleunion-dot-org/pull/106, so I'll close this one.
